import type { ThreatPattern } from "./types.js";

export const THREAT_PATTERNS: ThreatPattern[] = [
  // CRITICAL: Remote code execution
  {
    name: "CURL_PIPE_BASH",
    pattern: /curl\s+.*\|\s*(ba)?sh/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Curl piped to shell",
    description: "Downloads and executes remote code directly — classic supply chain attack vector.",
  },
  {
    name: "WGET_EXECUTE",
    pattern: /wget\s+.*&&\s*(ba)?sh/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Wget with shell execution",
    description: "Downloads and executes remote code via wget.",
  },
  {
    name: "EVAL_DYNAMIC",
    pattern: /eval\s*\(/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Dynamic eval() usage",
    description: "Uses eval() which can execute arbitrary code.",
  },
  {
    name: "BASE64_DECODE",
    pattern: /base64\s+(-d|--decode)/gi,
    severity: "critical",
    category: "obfuscation",
    title: "Base64 decode execution",
    description: "Decodes base64 content, often used to hide malicious payloads.",
  },
  {
    name: "PYTHON_EXEC",
    pattern: /python[3]?\s+-c/gi,
    severity: "critical",
    category: "remote_code_execution",
    title: "Python inline execution",
    description: "Executes inline Python code which may contain hidden payloads.",
  },

  // HIGH: Credential theft
  {
    name: "ENV_FILE_READ",
    pattern: /\.env|credentials|\.aws|\.ssh|keychain/gi,
    severity: "high",
    category: "credential_theft",
    title: "Sensitive file access",
    description: "Accesses credential files (.env, .aws, .ssh, keychain).",
  },
  {
    name: "API_KEY_EXFIL",
    pattern: /(ANTHROPIC|OPENAI|SLACK|DISCORD|TELEGRAM).*(_KEY|_TOKEN|_SECRET)/gi,
    severity: "high",
    category: "credential_theft",
    title: "API key reference",
    description: "References specific API keys/tokens that could be exfiltrated.",
  },
  {
    name: "DOTFILE_ACCESS",
    pattern: /~\/\.(openclaw|clawdbot|moltbot)\//gi,
    severity: "high",
    category: "credential_theft",
    title: "OpenClaw config access",
    description: "Accesses OpenClaw/Clawdbot/Moltbot configuration directories.",
  },
  {
    name: "SESSION_THEFT",
    pattern: /sessions\/\*\.jsonl/gi,
    severity: "high",
    category: "credential_theft",
    title: "Session data access",
    description: "Accesses session transcript files which may contain sensitive data.",
  },

  // HIGH: Network exfiltration
  {
    name: "WEBHOOK_SEND",
    pattern: /webhook\.(site|url)|discord\.com\/api\/webhooks/gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Webhook data exfiltration",
    description: "Sends data to webhook endpoints (common exfiltration method).",
  },
  {
    name: "BORE_TUNNEL",
    pattern: /bore\.pub|ngrok|localtunnel/gi,
    severity: "high",
    category: "data_exfiltration",
    title: "Tunnel service usage",
    description: "Uses tunneling services to expose local services or exfiltrate data.",
  },
  {
    name: "SUSPICIOUS_IP",
    pattern: /\b(?:91\.92\.242\.\d+|45\.61\.\d+\.\d+)\b/g,
    severity: "high",
    category: "data_exfiltration",
    title: "Known malicious IP",
    description: "Contains IP addresses associated with known ClawHavoc C2 infrastructure.",
  },

  // MEDIUM: Social engineering
  {
    name: "PREREQUISITE_INSTALL",
    pattern: /prerequisite|install.*first|run.*before|required.*dependency/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Prerequisite install trick",
    description: "Instructs users to install prerequisites — common social engineering tactic.",
  },
  {
    name: "COPY_PASTE_COMMAND",
    pattern: /copy.*paste.*terminal|run.*this.*command/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Copy-paste command instruction",
    description: "Instructs users to copy-paste commands into their terminal.",
  },
  {
    name: "FAKE_DEPENDENCY",
    pattern: /openclaw-core|moltbot-runtime|clawdbot-helper/gi,
    severity: "medium",
    category: "social_engineering",
    title: "Fake dependency reference",
    description: "References fake packages that mimic official OpenClaw components.",
  },

  // MEDIUM: Prompt injection
  {
    name: "IGNORE_INSTRUCTIONS",
    pattern: /ignore\s+(all\s+)?previous\s+instructions/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "Prompt injection — ignore instructions",
    description: "Attempts to override the AI agent's existing instructions.",
  },
  {
    name: "SYSTEM_OVERRIDE",
    pattern: /you\s+are\s+now|new\s+instructions|forget\s+everything/gi,
    severity: "medium",
    category: "prompt_injection",
    title: "Prompt injection — system override",
    description: "Attempts to redefine the AI agent's identity or instructions.",
  },
  {
    name: "MEMORY_MANIPULATION",
    pattern: /SOUL\.md|MEMORY\.md|AGENTS\.md/gi,
    severity: "medium",
    category: "persistence",
    title: "Memory/personality file manipulation",
    description: "References core personality or memory files, may attempt persistence.",
  },

  // LOW: Suspicious but not necessarily malicious
  {
    name: "SHELL_EXEC",
    pattern: /child_process|exec\(|spawn\(/gi,
    severity: "low",
    category: "code_execution",
    title: "Shell execution API",
    description: "Uses shell execution APIs — legitimate but worth noting.",
  },
  {
    name: "NETWORK_REQUEST",
    pattern: /fetch\(|axios|node-fetch|got\(/gi,
    severity: "low",
    category: "network",
    title: "Network request API",
    description: "Makes network requests — legitimate but worth reviewing targets.",
  },
  {
    name: "FILE_WRITE",
    pattern: /fs\.write|writeFileSync/gi,
    severity: "low",
    category: "file_system",
    title: "File write operation",
    description: "Writes to the filesystem — check what files are being modified.",
  },
];

// Top 100 popular ClawHub skills for typosquat detection
export const POPULAR_SKILLS = [
  "todoist-cli",
  "github-manager",
  "slack-assistant",
  "email-composer",
  "calendar-sync",
  "weather-forecast",
  "news-reader",
  "code-reviewer",
  "docker-helper",
  "aws-manager",
  "notion-sync",
  "jira-tracker",
  "spotify-controller",
  "home-assistant",
  "file-organizer",
  "pdf-reader",
  "translate-text",
  "image-generator",
  "web-scraper",
  "database-query",
  "git-assistant",
  "linux-admin",
  "python-helper",
  "react-builder",
  "api-tester",
  "markdown-editor",
  "csv-analyzer",
  "ssh-manager",
  "cron-scheduler",
  "log-analyzer",
];
